# Generated by Django 2.0.2 on 2018-02-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180214_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='picture',
            field=models.ImageField(blank=True, default=None, height_field=140, null=True, upload_to='', width_field=140),
        ),
    ]
