# Generated by Django 2.0.2 on 2018-02-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180214_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='picture',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
