# Generated by Django 2.0.2 on 2018-02-14 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180214_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Media'),
        ),
    ]
